import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { mapFreeExerciseDB } from '../src/lib/exerciseMapper.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.resolve(__dirname, '..')
const defaultSource = path.resolve(
  projectRoot,
  '..',
  '..',
  'free-exercise-db-main',
  'free-exercise-db-main',
  'dist',
  'exercises.json',
)
const sourceFile = process.env.FREE_EXERCISE_DB_JSON
  ? path.resolve(process.env.FREE_EXERCISE_DB_JSON)
  : defaultSource
const outputFile = path.join(projectRoot, 'src', 'data', 'freeExerciseDb.generated.js')

const raw = JSON.parse(await readFile(sourceFile, 'utf8'))
const mapped = raw.map(mapFreeExerciseDB)

const contents = `// Generated by scripts/importFreeExerciseDb.mjs from yuhonas/free-exercise-db.
// Do not edit this file by hand; regenerate it from the source JSON.

export const FREE_EXERCISE_DB_EXERCISES = ${JSON.stringify(mapped, null, 2)}
`

await mkdir(path.dirname(outputFile), { recursive: true })
await writeFile(outputFile, contents)

console.log(`Imported ${mapped.length} exercises from ${sourceFile}`)
console.log(`Wrote ${outputFile}`)
